### PR TITLE
Prepare 0.3.0 release

### PR DESCRIPTION
**Pull request by gingermusketeer**

### CODE REVIEW

**Comment by gingermusketeer** [comment]
@splattael Would you be able to merge this and push the gem up to ruby gems?

**Comment by splattael** [comment]
@gingermusketeer 

```
$ gem install rufo
Fetching: rufo-0.3.0.gem (100%)
Successfully installed rufo-0.3.0
1 gem installed
```

I totally forgot to release rufo :/ Sorry!

**Comment by splattael** [comment]
@gingermusketeer BTW, I've added you as a gem owner: https://rubygems.org/gems/rufo

Again, sorry for being late. Twice :disappointed:

**Comment by gingermusketeer** [comment]
@splattael No worries, we all have other things going on!

Thanks for doing the release and adding me to ruby gems :)

**Pull request merged**
