### PR TITLE
Remove space around binary config

### PR DESCRIPTION
**Pull request by gingermusketeer**
There was some disagreement about this in #2 so I thought a PR might be the best way to decide what to do.

IMO the `dynamic` option is somewhat synonymous with "inconsistent" and this seems to go against the goals in #2. Thoughts?

### CODE REVIEW

**Comment by splattael** [comment]
I suppose 4 :white_check_mark: approvals mean :twisted_rightwards_arrows: "Merge it"? :grin:

**Comment by gingermusketeer** [comment]
@bessey Any thoughts on this change?

**Comment by lucerion** [comment]
@gingermusketeer thank you!

**Comment by bessey** [comment]
belated 👍

**Pull request merged**
