### PR TITLE
Quote style

### PR DESCRIPTION
**Pull request by gurgeous**
See #74.

### CODE REVIEW

**Comment by gurgeous** [comment]
Oops - was I supposed to run rufo on rufo or something?

**Comment by gingermusketeer** [comment]
@gurgeous Yes that is right. Can you run `rake rufo`. Once that is done you should be able to run `rake ci` and have it pass.

**Comment by gurgeous** [comment]
done, thanks

**Comment by gingermusketeer** [comment]
@splattael Would you be able to do a release with this included?

**Comment by splattael** [comment]
@gingermusketeer Sure, good idea! I am not sure whether it's 0.2.1 or 0.3.0.
WDYT?

**Comment by gingermusketeer** [comment]
@splattael I think 0.3.0 makes sense given that it adds a nice new feature :)

**Comment by splattael** [comment]
@gingermusketeer I am sorry for not releasing 0.3.0 yet :/
I am back from shorttaken vacations and will take care of releasing 0.3.0 this week!

**Pull request merged**
