### PR TITLE
Add file encode option.  

### PR DESCRIPTION
**Pull request by megaya**
Since UTF-8 file causes syntax error, specify file encoding with option. 

```
$ rufo --encode=utf-8
```

#197

If you don't use magic comments, as in the issue, you may get an error.(`# encoding: UTF-8`)
The cause is the default character code setting.

```
// success
$ ruby -e 'puts __ENCODING__'
=> UTF-8

// error 
// Docker image is ruby:2.6.2
$ docker-compose exec web ruby -e 'puts __ENCODING__'
=> US-ASCII
```

The error is occurring when parsing with `ripper`.
https://github.com/ruby-formatter/rufo/blob/master/lib/rufo/formatter.rb#L24

So it was fixed to specify the encoding when reading the file.
https://github.com/megaya/rufo/blob/add-file-encode-option/lib/rufo/command.rb#L100

### CODE REVIEW

**Comment by gingermusketeer** [comment]
@megaya Thanks again for another PR ❤️

Looking at the [ruby docs](https://docs.ruby-lang.org/en/2.7.0/Encoding.html#class-Encoding-label-Script+encoding) for how this works when ruby runs it looks like:
- UTF-8 is the default
- If there is a magic comment then that is used. The encoding comment must contain `coding` followed by a `:` and then the encoding.
- There is a `-K` command line option to configure this but that should be avoided (I think we can ignore this case).

What do you think about making the following changes?
- Detect a magic comment and change to the encoding specified if present.
- Otherwise default to UTF-8.
- Remove the config option for now given that `-K` is not recommended.

**Comment by megaya** [comment]
@gingermusketeer Thank you for your reply!

*  Detect a magic comment and change to the encoding specified if present.

If you enter a magic comment, it will be corrected. However, applying this to all files is a daunting task.

*  Otherwise default to UTF-8.

Ruby file class inherits IO class. The IO class seems to use External encoding and Internal encoding.
[ruby docs](https://docs.ruby-lang.org/en/2.7.0/Encoding.html#class-Encoding-label-IO+encoding+example)

```ruby
string = "R\u00E9sum\u00E9"

open("transcoded.txt", "w:ISO-8859-1") do |io|
  io.write(string)
end

puts "raw text:"
p File.binread("transcoded.txt")
puts

open("transcoded.txt", "r:ISO-8859-1:UTF-8") do |io|
  puts "transcoded text:"
  p io.read
end
```

> While writing the file, the internal encoding is not specified as it is only necessary for reading. While reading the file both the internal and external encoding must be specified to obtain the correct result.


* Remove the config option for now given that -K is not recommended.

This change is different in nature from the `-K` option.  I just changed the read encoding of the file.

```ruby
# The value specified in the option becomes the `encode:` option of File.read
code = File.read(filename, encoding: @file_encode)
```

-------------------

But I don't think this fix is ​​the best solution. Options are more correct if they don't increase blindly.

I introduced rufo in the middle of development.  So it was hard to put magic comment (`encoding: utf-8`) in all files. I thought that some people would be as frustrated as me with this bug, so I fixed it.

Another thing, this problem may be displayed as a `syntax error`.  In the first place, you may not know the cause of the error. It may be better to get a character code error instead of a `syntax error`.

**Comment by gingermusketeer** [comment]
@megaya Thanks for the info. 

What do you think about making the default encoding UTF-8 and then we can look at handling magic comments in a future PR?

I think this means that we can change https://github.com/ruby-formatter/rufo/blob/a0706b40d3447d8cd5f9fc70051f57927d97abcb/lib/rufo/command.rb#L100
to something like:
`code = File.read(filename, encoding: "UTF-8")`

**Comment by megaya** [comment]
@gingermusketeer Thank you for your reply!

> What do you think about making the default encoding UTF-8 and then we can look at handling magic comments in a future PR?

Is it correct to change `File.read` to UTF-8 by default?
I think i have no problem!

**Comment by gingermusketeer** [comment]
@megaya I believe it is. Let's try it!

**Comment by megaya** [comment]
@gingermusketeer 
Hi.
It has changed. Are you satisfied with this change?

**Comment by megaya** [comment]
@gingermusketeer Thank you!!

**Pull request merged**
