### PR TITLE
format(Tests): introduce new test format

### LINKED ISSUE #10: Reformat tests
I'd like to have tests in separate files, with an in-file delimiter to separate original and expected. Something like

```ruby
def method arg
 arg
end

#~#

def method(arg)
  arg
end
```

### PR DESCRIPTION
**Pull request by danielma**
One major challenge working with the rufo codebase is difficulty in
reviewing and verifying the test cases. Because they are lots of
single line strings with `\n` characters, it's hard to tell what's
really going on.

This PR exists to break many of these tests out into the
`spec/source_specs` directory. Using a special magic syntax, we are
able to denote tests and options, and even name them. It's much easier
to look at a test and tell exactly what is inputted and expected as
the output.

Closes #10

### CODE REVIEW

**Comment by splattael** [comment]
@danielma Wow, this huge :purple_heart: :sparkles:
I like the idea a lot :+1:

Thank you!

**Comment by mjago** [comment]
Thanks for this PR @danielma - I've previously spoken to @splattael about just this thing on Gitter with the final goal being to auto-parse the resulting specs into nice viewable code snippets on some website somewhere. To that end it would be nice if we could have additional metadata to indicate catagories and perhaps sub-catagories to that end. Perhaps this PR is a good time to consider that?

**Comment by danielma** [comment]
@mjago definitely willing to consider it. What do you have in mind? We currently have the ability to group tests by file name and name each spec individually. If there's more you'd like, do let me know

**Comment by danielma** [comment]
I'm gonna merge this now, but I'd love to keep working on the tests, and am happy to do that going forward

**Pull request merged**
