### PR TITLE
[New formatter] Format hashes

### PR DESCRIPTION
**Pull request by gingermusketeer**
There is some weird formatting on this inside nested body statements but that should be resolved when the bodies themselves are formatted with the new approach.

@mjago I tried to start off with a completely new formatter as we discussed but I was not able to make much progress so I have reverted to this approach of picking something off and getting it working. Hopefully that makes sense.

### CODE REVIEW

**Comment by splattael** [comment]
@gingermusketeer Could you please rebase against the latest `master`? :neckbeard:

**Comment by mjago** [comment]
@gingermusketeer No problem. I haven't looked at this since we spoke (not doing any Ruby at present). I'll try to make time to look at issues over the next few days 👍

**Comment by gingermusketeer** [comment]
@splattael I merged master into this branch. Would you prefer I undo that and rebase?

**Comment by splattael** [comment]
@gingermusketeer Oops, sorry for my obviously very late reply :/

Yeah, rebasing would be great :+1:

**Comment by gingermusketeer** [comment]
@splattael I looked into rebasing this but it was more complicated then I wanted to tackle. Given that this is not going into master I am going to go a head and merge this. Suspect that we will end up squashing all these commits and rebasing against master prior to merging the `new-formatter` branch.

**Pull request merged**
