### PR TITLE
Start using RuboCop on the Rufo codebase

### PR DESCRIPTION
**Pull request by ndbroadbent**
I added RuboCop as a dependency, and I set up a default `.rubocop_todo.yml` and `.rubocop.yml`. (There are currently 49 offenses to fix.)

I'd love to see the Rufo project using RuboCop, and vice versa.

EDIT: Actually [RuboCop crashes when used with the `--auto-correct` option](https://github.com/rubocop-hq/rubocop/issues/6489). (Similar issue to #130, because Rufo also breaks on the RuboCop codebase.)

### CODE REVIEW

**Comment by gingermusketeer** [comment]
I am not sure what other folks on this project think but here are my thoughts on adding RuboCop to the code base:

 ## 1. Use the recommended settings.
Rufo is becoming more and more opinionated and I think this is a good thing. At the very minimum we should have good defaults.

I think we should apply this to other tools that are in the developer utility space hence I think we should use whatever RuboCop recommends as defaults. This would be similar to `eslint/recommended` from the JS world.

## 2. All RuboCop styling rules should be disabled
Rufo is the source of truth for styling in this repo and sticking to one will simplify determining if rufo is doing a good job without another tool confusing the formatting it produces.

Ideally Rufo would use RuboCop for linting and RuboCop would use Rufo for styling. This way there is a separation of concerns and the tools do no conflict. Maybe one day we can have a ruby standard formatter and linter.

With this in mind I would see the RuboCop configuration being something like (not sure if this is possible):
```yml
inherits: RuboCop/recommended
Style:
  disabled: true
```


Let me know what you think of that.

**Comment by ndbroadbent** [comment]
1. makes sense to me! But for 2., I just had a look through the Style and Layout cops, and they're a mixed bag.

The majority of the [Layout cops](https://rubocop.readthedocs.io/en/latest/cops_layout/) are about formatting, alignment, whitespace, etc., but many of them are also linting rules. Examples:

[`Layout/ClassStructure` rule](https://rubocop.readthedocs.io/en/latest/cops_layout/#layoutclassstructure). (Checks if everything is in the right order.) That seems like a linting issue instead of a formatting issue.

Also [`Layout/EmptyComment`](https://rubocop.readthedocs.io/en/latest/cops_layout/#layoutemptycomment), and [`Layout/EmptyLineAfterGuardClause`](https://rubocop.readthedocs.io/en/latest/cops_layout/#layoutemptylineafterguardclause). Although it would be great if `rufo` could detect guard clauses and insert an empty line after them.

Same for the [Style cops](https://rubocop.readthedocs.io/en/latest/cops_style/), like`Style/ArrayJoin`:

```ruby
# bad
%w(foo bar baz) * ","

# good
%w(foo bar baz).join(",")
```

I would suggest to just see how it goes first, and disable or configure any rules whenever necessary. If there are any conflicts then it would be good to start a discussion on [`ruby-style-guide`](https://github.com/rubocop-hq/ruby-style-guide) (or [rubocop](https://github.com/rubocop-hq/rubocop)), or find some previous discussions. It would be great to end up with a commented `.rubocop.yml` or a Wiki page that shows any differences.

I also think that RuboCop and Rufo will probably agree on 99% of the `Style` and `Layout` rules, and there will just be a few small details to iron out. And any differences can be configured or disabled in the RuboCop config. So disabling all the `Layout` and `Style` cops would probably be easier, but I don't know if that's the best way forward, or if it's even necessary.

**Comment by ndbroadbent** [comment]
Actually forgot to re-run `rufo .` to check. `rufo` produces some really gross code, with one-line conditionals:

```diff
-    if syntax_error then CODE_ERROR
-    elsif changed      then CODE_CHANGE
-    else                   CODE_OK
-    end
+    if syntax_error then CODE_ERROR     elsif changed then CODE_CHANGE     else CODE_OK end
```

I've disabled this RuboCop rule for now (`Style/OneLineConditional`), but would be better to fix this in rufo.

This is another one:

```
lib/rufo/settings.rb:20:63: C: Style/StringLiteralsInInterpolation: Prefer single-quoted strings inside interpolations.
             "values are: #{valid_options.map(&:inspect).join(", ")}"
```

Not sure about that. Have also turned that off in RuboCop.

Anyway, now it's at the point where you can run `rubocop -a; rufo .; rubocop -a; rufo .` and there will be no changes.

**Comment by ndbroadbent** [comment]
Ah, the `Style/EmptyCaseCondition` cop is interesting. This code:

```ruby
    case
    when syntax_error then CODE_ERROR
    when changed      then CODE_CHANGE
    else                   CODE_OK
    end
```

Is auto-corrected by RuboCop:

```
Offenses:

lib/rufo/command.rb:90:5: C: [Corrected] Style/EmptyCaseCondition: Do not use empty case condition, instead use an if expression.
    case
    ^^^^

1 file inspected, 1 offense detected, 1 offense corrected
```

The resulting code:

```ruby
    if syntax_error then CODE_ERROR
    elsif changed      then CODE_CHANGE
    else                   CODE_OK
    end
```

Then `rufo lib/rufo/command.rb` produces:

```ruby
if syntax_error then CODE_ERROR     elsif changed then CODE_CHANGE     else CODE_OK end
```


I don't like how RuboCop ruins the indentation. But I also don't like how Rufo puts the whole thing on one line.

To avoid this issue, I've disabled the `Style/EmptyCaseCondition` cop for now.

**Pull request closed without merging**
