### PR TITLE
Fix kwrest_param bug in ruby 2.5.0

### LINKED ISSUE #20: Unhandled node: kwrest_param at [[2, 12], :on_rparen, ")"]
We have 2 test failures on ruby-head:
https://travis-ci.org/ruby-formatter/rufo/jobs/275214575

```
Rufo::Bug:
       Unhandled node: kwrest_param at [[2, 12], :on_rparen, ")"]
```

### PR DESCRIPTION
**Pull request by gingermusketeer**
Looks to be related to this change https://bugs.ruby-lang.org/issues/12387

Fixes #20.

### CODE REVIEW

**Comment by gingermusketeer** [comment]
I am still getting my head around how this all works so I am not sure exactly why this resolves the issue. I started by copying the method from here: https://github.com/ruby-formatter/rufo/blob/aad0f24923fe3628d5007630d4646a875c4c3bf8/lib/rufo/formatter.rb#L1729-L1740

I don't quite understand why the `consume_op "*"` call is not required, or at least something similar.

**Comment by danielma** [comment]
> I don't quite understand why the consume_op "*" call is not required, or at least something similar.

I haven't looked deeply, but my guess is that in `[:kwrest_param, name]`, `name` includes `[:rest_param, ...]` and rufo handles it correctly

**Comment by splattael** [comment]
:+1: @gingermusketeer :purple_heart:

**Comment by lucerion** [comment]
Looks good to me! :+1: Thank you @gingermusketeer!

**Comment by gingermusketeer** [comment]
No problem, glad to help :)

**Comment by gingermusketeer** [comment]
Any chance of getting this merged?

**Comment by splattael** [comment]
@gingermusketeer Merged :twisted_rightwards_arrows:! Thanks again :purple_heart:

**Pull request merged**
