### PR TITLE
Promote rake to runtime dependency

### LINKED ISSUE #231: Missing runtime dependency: rake
If I try to install this package I get the following error:
```
...lib/ruby/gems/2.6.0/gems/rufo-0.11.0/lib/rufo/file_finder.rb:2:in `require': cannot load such file -- rake/file_list (LoadError)
```

I notice that `rake` is used, but not defined as a dependency (only dev dependency):
https://github.com/ruby-formatter/rufo/blob/c10652b90be5c8e8bd25e5a4c8030ec0e36acbce/lib/rufo/file_finder.rb#L2

### PR DESCRIPTION
**Pull request by terlar**
lib/rufo/file_finder.rb
2:require "rake/file_list"

Fix #231

### CODE REVIEW

**Comment by gingermusketeer** [comment]
@terlar Thanks for bringing this up. Definitely need to resolve this as it is not working as intended. I was expecting that because rake is included by default when ruby is installed that this wouldn't be needed.

One of the goals of Rufo is to not have any dependencies so I would like to avoid promoting rake to a runtime dependency. Instead I am wondering about pulling in a cut down version of https://github.com/ruby/rake/blob/master/lib/rake/file_list.rb
I think there is a lot that we don't need in there.

Would you be interested in having a go at removing the need for rake?

**Comment by terlar** [comment]
Thank you for your reply. I think it might be an edge case, but at least in the case of Nix where you have a pure environment this is the case, and perhaps in some other cases as well.

I like that you don't want to have any dependencies and it is in fact one of the points that make me want to use rufo as well.

My ruby is a bit rusty recently as I haven't used it for a while, but I might take a stab at it.

Thank you.

**Comment by gingermusketeer** [comment]
@terlar great! Feel free to push up any work in progress and I can help out if you like :)

**Comment by gingermusketeer** [comment]
@terlar I have tackled this in #238 I hope that is okay!

**Comment by terlar** [comment]
Of course, thank you for fixing it. I do think it is nice for the project to truly be fully dependency free now :)

**Pull request closed without merging**
