### PR TITLE
Remove space config

### PR DESCRIPTION
**Pull request by gingermusketeer**
This removes most of the space related configuration as part of #2. From the current discussions in #2 the changes being made here appear to have agreement on the behaviour.

The remaining configuration related to spacing had some discussion around it so I think it would be best to address that in a separate PR.

This is quite a big diff :( let me know if I should break this up!

### CODE REVIEW

**Comment by bessey** [comment]
One though. I'm not sure what constitutes a breaking change for a formatter, but I imagine suddenly ignoring parts of someone's custom config is one of them, so we should at very least document that in the Changelog.

Perhaps we should even detect the no longer supported options, and warn the user at runtime? Not sure how one can warn other than STDERR + bad exit code though, which seems a bit ugly for those running via an editor extension.

**Comment by splattael** [comment]
@gingermusketeer One thing. Do you mind to update https://github.com/ruby-formatter/rufo/wiki/Settings?

**Comment by gingermusketeer** [comment]
@splattael It does not look like it is possible to create a PR against the wiki repo and I don't have permission to update the wiki pages. I could create a gist with the new content if that works?

@bessey Good catch, I think detecting invalid config is a great idea, definitely help prevent spelling mistakes causing frustration as well as changes to rufo. I will update the change log when I get a moment.

**Comment by mjago** [comment]
Changes are great - thanks @gingermusketeer ! I think the invalid config detection is a separate PR. I'm undecided whether a typo should cause "no formatting" and an error rather than good formatting and no error?

**Comment by lucerion** [comment]
@gingermusketeer good job! Thank you!

**Comment by splattael** [comment]
> @splattael It does not look like it is possible to create a PR against the wiki repo and I don't have permission to update the wiki pages. I could create a gist with the new content if that works?

@gingermusketeer Oh, right :flushed:  I've just invited you as a collaborator :grin:

**Comment by gingermusketeer** [comment]
@splattael Awesome!! Thanks a lot. I have really enjoyed working on this project so far :)

**Comment by gingermusketeer** [comment]
@mjago Thanks for spotting that. I have merged in the changes from master and cleaned that up.

**Comment by mjago** [comment]
Thanks @gingermusketeer ! I formatted the ruby spec corpus with the changes and all looks good from what I have seen. And fast :+1:

**Comment by gingermusketeer** [comment]
@splattael I have updated the settings page by removing the old config options that were described there.

**Comment by splattael** [comment]
@gingermusketeer Thank you! :green_heart: 

I've added a warning about the future removal of the remaining settings at https://github.com/ruby-formatter/rufo/wiki/Settings#warning-settings-are-going-away-warning.

Feel free to correct my English :no_mouth:

**Pull request merged**
